// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcfHV5sI2rJpv2KB9wR_L5hw4DZCqK4pQ',
    appId: '1:867626118424:android:9175f2470d837c2a30026d',
    messagingSenderId: '867626118424',
    projectId: 'send-data-c87cb',
    storageBucket: 'send-data-c87cb.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-I2gMKbr528BVYNFPckpMw8t-nYMf5iU',
    appId: '1:867626118424:web:7f2f52bd24cd1fa030026d',
    messagingSenderId: '867626118424',
    projectId: 'send-data-c87cb',
    authDomain: 'send-data-c87cb.firebaseapp.com',
    storageBucket: 'send-data-c87cb.firebasestorage.app',
    measurementId: 'G-H2FB62K3T7',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-I2gMKbr528BVYNFPckpMw8t-nYMf5iU',
    appId: '1:867626118424:web:717842b733389fe930026d',
    messagingSenderId: '867626118424',
    projectId: 'send-data-c87cb',
    authDomain: 'send-data-c87cb.firebaseapp.com',
    storageBucket: 'send-data-c87cb.firebasestorage.app',
    measurementId: 'G-6DX6JZPWXV',
  );

}